language: python

python:
 - "2.7"

env:
 - DJANGO=1.5

install:
 - pip install -q Django==$DJANGO
 - pip install python-swiftclient
 - pip install requests
 - pip install git+git://github.com/cschwede/django-swiftbrowser.git#egg=swiftbrowser


script: python runtests.py

notifications:
 email:
  recipients:
   - github@cschwede.de
